defaults:
  - _base
  - _self_

name: vpt

train_entry: crafterdojo.agent.vpt.bc_train.main
eval_entry: crafterdojo.agent.vpt.eval.main

model: models/craftervpt/cvpt_tiny.model
weights: null

train_dataset:
  dataset_root: "CrafterDojo_Data/filtered_20"
  data_split: "[0:18000]"
  episode_cutoff: null

val_dataset:
  dataset_root: "CrafterDojo_Data/filtered_20"
  data_split: "[18000:19000]"
  episode_cutoff: null

# hyperparameters for training
T: 640
batch_size: 32
num_workers: 8

trunc_t: 64
learning_rate: 5e-4
min_learning_rate: 1e-6
n_samples: 1_000
n_epochs: 10
warmup_samples: 10_000_000
weight_decay: 1e-4
max_grad_norm: 5

# logging
log_freq: 100
save_freq: 1000
snapshot_every_n_samples: 10_000_000
val_freq: 3500
