defaults:
  - _base
  - _self_

name: ppo

train_entry: crafterdojo.agent.ppo.train.train_entry
eval_entry: crafterdojo.agent.ppo.eval.eval_entry

eval:
  load: null

n_envs: 4
live_bonus: 0
death_penalty: 0

learning_rate: 3e-4
n_steps: 512
batch_size: 512
n_epochs: 10
gamma: 0.999
gae_lambda: 0.95
total_timesteps: 1_000_000

save_freq: 1000
eval_freq: 5000
n_eval_episodes: 30
